version: '3.8'

services:
  nginx:
    build: 
      context: nginx
    container_name: nginx
    ports:
    - '8080:8080'
    depends_on:
    - app
    networks:
      - node-network

  app:
    build: 
      context: node
    container_name: app      
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 300s -wait-retry-interval 30s && npm install && node node.js"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
      container_name: db  
      restart: always
      tty: true
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./init.sql:/data/application/init.sql
        - ./mysql:/var/lib/mysql2
      networks:
        - node-network
    
    
        

networks:
  node-network:
    driver: bridge
    
